[colors.primary]
background = "#1c1c1c"
foreground = "#d4d4d4"
bright_foreground = "#e4e4e4"
dim_foreground = "#808080"

[colors.cursor]
text = "#1c1c1c"
cursor = "#e6b450"

[colors.search.matches]
background = "#174c4c"

[colors.search.focused_match]
background = "#3e1215"

[colors.selection]
background = "#322c3e"

[colors.normal]
black = "#4e4e4e"
red = "#da5757"
green = "#7ed962"
yellow = "#e6b450"
blue = "#5785b8"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#d4d4d4"

[colors.bright]
black = "#8a8a8a"
red = "#da5757"
green = "#7ed962"
yellow = "#e6b450"
blue = "#5785b8"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#e4e4e4"

[colors.dim]
black = "#262626"
red = "#3e1619"
green = "#3e522b"
yellow = "#1b231c"
blue = "#1c3a5b"
magenta = "#322c3e"
cyan = "#174c4c"
white = "#808080"

[colors]
indexed_colors = [
    { index = 238, color = "#4e4e4e" },
    { index = 242, color = "#8a8a8a" },
    { index = 237, color = "#262626" },

    { index = 160, color = "#da5757" },
    { index = 197, color = "#da5757" },
    { index = 52, color = "#3e1619" },

    { index = 34, color = "#7ed962" },
    { index = 40, color = "#7ed962" },
    { index = 22, color = "#3e522b" },

    { index = 226, color = "#e6b450" },
    { index = 227, color = "#e6b450" },
    { index = 220, color = "#1b231c" },

    { index = 33, color = "#5785b8" },
    { index = 39, color = "#5785b8" },
    { index = 18, color = "#1c3a5b" },

    { index = 140, color = "#d2a6ff" },
    { index = 141, color = "#d2a6ff" },
    { index = 92, color = "#322c3e" },

    { index = 43, color = "#95e6cb" },
    { index = 44, color = "#95e6cb" },
    { index = 31, color = "#174c4c" },

    { index = 249, color = "#d4d4d4" },
    { index = 250, color = "#e4e4e4" },
    { index = 248, color = "#808080" },

    { index = 196, color = "#ff0000" },

    { index = 234, color = "#1c1c1c" },
    # lighter
    { index = 235, color = "#252525" },
    { index = 236, color = "#3c3c3b" },
    # darker
    { index = 233, color = "#080808" },
    { index = 232, color = "#000000" },
    # special
    { index = 128, color = "#322c3e" },


    { index = 245, color = "#d4d4d4" },
    # lighter
    { index = 246, color = "#e4e4e4" },
    { index = 247, color = "#eeeeee" },
    # darker
    { index = 244, color = "#808080" },
    { index = 243, color = "#444444" },
    # special
    { index = 177, color = "#d2a6ff" },
]
