pre-commit:
  commands:
    formatter-check:
      run: make formatter-check
    linter-check:
      run: make linter-check
    flake-check:
      run: make flake-check
    spellchecker-check:
      run: make spellchecker-check
