[colors.primary]
background = "#202020"
foreground = "#d4be98"

[colors.cursor]
text = "#202020"
cursor = "#d8a657"

[colors.search.matches]
background = "#333e34"

[colors.search.focused_match]
background = "#3c1f1e"

[colors.selection]
background = "#332733"

[colors.normal]
black = "#504945"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.bright]
black = "#928374"
red = "#ea6962"
green = "#a8b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#ddc7a1"

[colors.dim]
black = "#32302f"
red = "#3c1f1e"
green = "#32361a"
yellow = "#4e422f"
blue = "#0d3138"
magenta = "#332733"
cyan = "#333e34"
white = "#918474"

[colors]
indexed_colors = [
    { index = 52, color = "#3c1f1e" },
    { index = 22, color = "#32361a" },
    { index = 220, color = "#4e422f" },
    { index = 18, color = "#0d3138" },
    { index = 92, color = "#332733" },
    { index = 31, color = "#333e34" },

    { index = 196, color = "#ff0000" },

    { index = 236, color = "#32302e" },
    { index = 235, color = "#282726" },
    { index = 234, color = "#202020" }, # default
    { index = 233, color = "#1d2021" },
    { index = 232, color = "#141617" },
    { index = 128, color = "#32361a" },

    { index = 247, color = "#dfcbab" },
    { index = 246, color = "#ddc7a1" },
    { index = 245, color = "#d4be98" }, # default
    { index = 244, color = "#928374" },
    { index = 243, color = "#504945" },
    { index = 177, color = "#a8b665" },
]
