[colors.primary]
background = '#282828'
foreground = '#ebdbb2'
dim_foreground = "#ebdbb2"
bright_foreground = "#ebdbb2"

[colors.normal]
black = '#1d2021'
red = "#ea6962"
green = "#a9b665"
blue = "#7daea3"
yellow = "#e78a4e"
magenta = "#d3869b"
cyan = "#89b482"
white = '#504945'

[colors.bright]
black = '#7c6f64'
red = "#ea6962"
green = "#a9b665"
blue = "#7daea3"
yellow = "#d8a657"
magenta = "#945e80"
cyan = "#89b482"
white = '#ebdbb2'