[colors.primary]
background = "#f9f5d7"
foreground = "#654735"

[colors.cursor]
text = "#f9f5d7"
cursor = "#b47109"

[colors.search.matches]
background = "#a3b592"

[colors.search.focused_match]
background = "#fec9a4"

[colors.selection]
background = "#c6a7a3"

[colors.normal]
black = "#443024"
red = "#c14a4a"
green = "#6c782e"
yellow = "#b47109"
blue = "#45707a"
magenta = "#945e80"
cyan = "#4c7a5d"
white = "#654735"

[colors.bright]
black = "#543b2c"
red = "#c14a4a"
green = "#6c782e"
yellow = "#b47109"
blue = "#45707a"
magenta = "#945e80"
cyan = "#4c7a5d"
white = "#ae8065"

[colors.dim]
black = "#363a4f"
red = "#fec9a4"
green = "#d0d9a5"
yellow = "#e5d8b1"
blue = "#ced0b3"
magenta = "#c6a7a3"
cyan = "#a3b592"
white = "#4e3829"

[colors]
indexed_colors = [
  { index = 52, color = "#fec9a4" },
  { index = 22, color = "#d0d9a5" },
  { index = 220, color = "#e5d8b1" },
  { index = 18, color = "#ced0b3" },
  { index = 92, color = "#c6a7a3" },
  { index = 31, color = "#a3b592" },

  { index = 196, color = "#ff0000" },

  { index = 236, color = "#cec2a2" },
  { index = 235, color = "#f5eabf" },
  { index = 234, color = "#f9f5d7" }, # default
  { index = 233, color = "#faf6dd" },
  { index = 232, color = "#fbf9e5" },
  { index = 128, color = "#d0d9a5" },

  { index = 247, color = "#443024" },
  { index = 246, color = "#543b2c" },
  { index = 245, color = "#654735" }, # default
  { index = 244, color = "#ae8065" },
  { index = 243, color = "#c4a28f" },
  { index = 177, color = "#6c782e" },
]
