- name: Set plugins urls
  set_fact:
    plugins_urls:
      - "https://github.com/jeffreytse/zsh-vi-mode.git"
      - "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      - "https://github.com/zsh-users/zsh-autosuggestions.git"
      - "https://github.com/Aloxaf/fzf-tab.git"
      - "https://github.com/MichaelAquilina/zsh-you-should-use.git"

- name: Download plugins
  git:
    repo: "{{ item }}"
    dest: "{{ xdg_data_home_path }}/zsh/plugins/{{ (item | urlsplit('path') | basename) | regex_replace('.git$', '') }}"
    depth: 1
  loop: "{{ plugins_urls }}"

- name: Backup previous zsh config
  include_role:
    name: backup_config
  vars:
    config_src_path: "{{ home_path }}/.zshrc"

- name: Symlink zsh config
  file:
    src: "{{ role_files_path }}/.zshrc"
    dest: "{{ home_path }}/.zshrc"
    state: link
