[colors.primary]
background = "#1c1c1c"
foreground = "#d4d4d4"

[colors.cursor]
text = "#1c1c1c"
cursor = "#5785b8"

[colors.search.matches]
background = "#174c4c"

[colors.search.focused_match]
background = "#3e1215"

[colors.selection]
background = "#322c3e"

[colors.normal]
black = "#4e4e4e"
red = "#da5757"
green = "#7ed962"
yellow = "#e6b450"
blue = "#5785b8"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#d4d4d4"

[colors.bright]
black = "#8a8a8a"
red = "#da5757"
green = "#7ed962"
yellow = "#e6b450"
blue = "#5785b8"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#e4e4e4"

[colors.dim]
black = "#262626"
red = "#3e1619"
green = "#3e522b"
yellow = "#1b231c"
blue = "#1c3a5b"
magenta = "#322c3e"
cyan = "#174c4c"
white = "#808080"

[colors]
indexed_colors = [
    { index = 52, color = "#3e1619" },
    { index = 22, color = "#3e522b" },
    { index = 220, color = "#1b231c" },
    { index = 18, color = "#1c3a5b" },
    { index = 92, color = "#322c3e" },
    { index = 31, color = "#174c4c" },

    { index = 196, color = "#ff0000" },

    { index = 236, color = "#3c3c3b" },
    { index = 235, color = "#252525" },
    { index = 234, color = "#1c1c1c" }, # default
    { index = 233, color = "#080808" },
    { index = 232, color = "#000000" },
    { index = 128, color = "#1c3a5b" },

    { index = 247, color = "#eeeeee" },
    { index = 246, color = "#e4e4e4" },
    { index = 245, color = "#d4d4d4" }, # default
    { index = 244, color = "#8a8a8a" },
    { index = 243, color = "#4e4e4e" },
    { index = 177, color = "#5785b8" },
]
