[colors.primary]
background = "#f8f9fa"
foreground = "#515151"

[colors.cursor]
text = "#f8f9fa"
cursor = "#365ec1"

[colors.search.matches]
background = "#9fdac6"

[colors.search.focused_match]
background = "#f0b2b4"

[colors.selection]
background = "#dae3f7"

[colors.normal]
black = "#7f7f7f"
red = "#bd1e0c"
green = "#438c27"
yellow = "#845d00"
blue = "#365ec1"
magenta = "#7a3e9d"
cyan = "#2c7960"
white = "#515151"

[colors.bright]
black = "#c3c8cc"
red = "#bd1e0c"
green = "#438c27"
yellow = "#845d00"
blue = "#365ec1"
magenta = "#7a3e9d"
cyan = "#2c7960"
white = "#4a505a"

[colors.dim]
black = "#787878"
red = "#f0b2b4"
green = "#dce8ca"
yellow = "#cbbb9f"
blue = "#dae3f7"
magenta = "#e9ddf7"
cyan = "#9fdac6"
white = "#979797"

[colors]
indexed_colors = [
    { index = 52, color = "#f0b2b4" },
    { index = 22, color = "#dce8ca" },
    { index = 220, color = "#cbbb9f" },
    { index = 18, color = "#dae3f7" },
    { index = 92, color = "#e9ddf7" },
    { index = 31, color = "#9fdac6" },

    { index = 196, color = "#ff0000" },

    { index = 236, color = "#d2d4d7" },
    { index = 235, color = "#f0f1f2" },
    { index = 234, color = "#f8f9fa" }, # default
    { index = 233, color = "#fcfdfd" },
    { index = 232, color = "#fefefe" },
    { index = 128, color = "#e9ddf7" },

    { index = 247, color = "#1e222a" },
    { index = 246, color = "#4a505a" },
    { index = 245, color = "#515151" }, # default
    { index = 244, color = "#7f7f7f" },
    { index = 243, color = "#adb4ba" },
    { index = 177, color = "#7a3e9d" },
]
