# Gruvbox material hard dark
colors:
  primary:
    background: "0x1d2021"
    foreground: "0xd4be98"

  normal:
    black: "0x4E4E4E"
    red: "0xea6962"
    green: "0xa9b665"
    yellow: "0xe78a4e"
    blue: "0x7daea3"
    magenta: "0xd3869b"
    cyan: "0x89b482"
    white: "0xdfbf8e"

  bright:
    black: "0x504945"
    red: "0xea6962"
    green: "0xa9b665"
    yellow: "0xe78a4e"
    blue: "0x7daea3"
    magenta: "0xd3869b"
    cyan: "0x89b482"
    white: "0x928374"
