[colors.bright]
black = "0x504945"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0x928374"
yellow = "0xe78a4e"

[colors.normal]
black = "0x4E4E4E"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x1d2021"
foreground = "0xd4be98"
