import = [
    "~/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml",
]

[env]
term = "xterm-256color"

[window]
decorations = "Buttonless"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

[window.dimensions]
columns = 115
lines = 40

[window.padding]
x = 1

[font]
size = 14

[font.normal]
# family = "FiraMono Nerd Font"
# family = "FiraCode Nerd Font"
family = "JetBrainsMono NF"
# family = "MartianMono NF"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[mouse]
hide_when_typing = true
