import = [
    # "~/.config/alacritty/themes/gruvbox/gruvbox-material-hard-dark.toml",
    # "~/.config/alacritty/themes/catppuccin/catppuccin-frappe.toml",
    "~/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml",
    # "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml",
    ]

[font]
size = 16

[font.bold]
style = "Regular"

[font.normal]
family = "FiraMono Nerd Font"

[window]
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 115
lines = 40
