import = [
    # "~/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml",
    # "~/.config/alacritty/themes/gruvbox-material/gruvbox-material-hard-dark.toml",
    # "~/.config/alacritty/themes/ayu/ayu-dark.toml",
    "~/.config/alacritty/themes/monosami/monosami-dark.toml",
]

[env]
term = "xterm-256color"

[window]
decorations = "Buttonless"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

[window.dimensions]
columns = 115
lines = 40

[window.padding]
x = 1

[font]
size = 16
offset.x = 0
offset.y = 9

[font.normal]
# family = "FiraMono Nerd Font"
# family = "FiraCode Nerd Font"
# family = "JetBrainsMono NF"
# family = "MartianMono NF"
family = "ZedMono NF Extd"

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[mouse]
hide_when_typing = true
