import = [
    # "~/.config/alacritty/themes/gruvbox/gruvbox-dark.toml",
    # "~/.config/alacritty/themes/gruvbox-material/gruvbox-material-dark.toml",
    "~/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml",
    ]

[font]
size = 16

[font.normal]
# family = "FiraMono Nerd Font"
family = "JetBrainsMono Nerd Font"

[window]
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 115
lines = 40

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true
