import = ["/Users/stounfo/.config/alacritty/themes/gruvbox/gruvbox-material-hard-dark.toml"]

[font]
size = 16

[font.bold]
style = "Regular"

[font.normal]
family = "FiraMono Nerd Font"

[window]
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 115
lines = 40
