- name: Install ripgrep
  package:
    name: ripgrep
    state: latest

- name: Backup previous ripgrep config
  include_role:
    name: backup_config
  vars:
    config_src_path: "{{ xdg_config_home_path }}/.ripgreprc"

- name: Symlink ripgrep config
  file:
    src: "{{ role_files_path }}/.ripgreprc"
    dest: "{{ xdg_config_home_path }}/.ripgreprc"
    state: link
