- name: Install ghostty
  community.general.homebrew_cask:
    name: ghostty
    state: latest
    install_options: force


- name: Backup previous ghostty config
  include_role:
    name: backup_config
  vars:
    config_src_path: "{{ xdg_config_home_path }}/ghostty"


- name: Ensure .config/ghostty dir exists
  file:
    path: "{{ xdg_config_home_path }}/ghostty"
    state: directory


- name: Symlink ghostty config
  file:
    src: "{{ role_files_path }}/ghostty"
    dest: "{{ xdg_config_home_path }}/ghostty"
    state: link
    force: true
