- name: Install tmux
  package:
    name: tmux
    state: latest

- name: Backup previous tmux config
  include_role:
    name: backup_config
  vars:
    config_src_path: "{{ xdg_config_home_path }}/tmux"

- name: Symlink tmux config
  file:
    src: "{{ role_files_path }}/tmux"
    dest: "{{ xdg_config_home_path }}/tmux"
    state: link

- name: Ensure scripts are executable
  ansible.builtin.file:
    path: "{{ xdg_config_home_path }}/tmux/scripts"
    state: directory
    mode: "0755"
