[colors.primary]
background = "#24273A"
foreground = "#cad3f5"
bright_foreground = "#cad3f5"

[colors.normal]
black = "#1e2030"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#c6a0f6"
cyan = "#8bd5ca"
white = "#363a4f"

[colors.bright]
black = "#6e738d"
red = "#ed8796"
green = "#a6da95"
yellow = "#f5a97f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#cad3f5"
