[colors.primary]
background = "#24273a"
foreground = "#cad3f5"

[colors.cursor]
text = "#24273a"
cursor = "#eed49f"

[colors.search.matches]
background = "#455c6d"

[colors.search.focused_match]
background = "#553f51"

[colors.selection]
background = "#5f507b"

[colors.normal]
black = "#5b6078"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#cad3f5"

[colors.bright]
black = "#9399b2"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#d8dff8"

[colors.dim]
black = "#363a4f"
red = "#553f51"
green = "#455451"
yellow = "#72685d"
blue = "#2e354d"
magenta = "#5f507b"
cyan = "#455c6d"
white = "#6e738d"

[colors]
indexed_colors = [
  { index = 52, color = "#553f51" },
  { index = 22, color = "#455451" },
  { index = 220, color = "#72685d" },
  { index = 18, color = "#2e354d" },
  { index = 92, color = "#5f507b" },
  { index = 31, color = "#455c6d" },

  { index = 196, color = "#ff0000" },

  { index = 236, color = "#40445a" },
  { index = 235, color = "#2f3348" },
  { index = 234, color = "#24273a" }, # default
  { index = 233, color = "#1e2030" },
  { index = 232, color = "#181926" },
  { index = 128, color = "#5f507b" },

  { index = 247, color = "#e5eafa" },
  { index = 246, color = "#d8dff8" },
  { index = 245, color = "#cad3f5" }, # default
  { index = 244, color = "#9399b2" },
  { index = 243, color = "#5b6078" },
  { index = 177, color = "#c6a0f6" },
]
