- name: Install pgcli
  package:
    name: pgcli
    state: latest


- name: Backup previous pgcli config
  include_role:
    name: backup_config
  vars:
    config_src_path: "{{ xdg_config_home_path }}/pgcli"


- name: Symlink pgcli config
  file:
    src: "{{ role_files_path }}/pgcli"
    dest: "{{ xdg_config_home_path }}/pgcli"
    state: link
