- name: Install pgcli
  package:
    name: pgcli
    state: latest


- name: Backup previous pgcli config
  include_role:
    name: backup_config
  vars:
    config_src_path: "{{ xdg_config_home_path }}/pgcli/config"


- name: Ensure .config/pgcli dir exists
  file:
    path: "{{ xdg_config_home_path }}/pgcli"
    state: directory


- name: Symlink pgcli config
  file:
    src: "{{ role_files_path }}/config"
    dest: "{{ xdg_config_home_path }}/pgcli/config"
    state: link
