- name: Install nvim
  package:
    name: nvim
    state: latest


- name: Backup previous nvim config
  include_role:
    name: backup_config
  vars:
    config_src_path: "{{ xdg_config_home_path }}/nvim"


- name: Download nvim config
  git:
    repo: "https://github.com/stounfo/nvim"
    dest: "{{ xdg_config_home_path }}/nvim"
