[colors.primary]
background = "#0d1017"
foreground = "#bfbdb6"
bright_foreground = "#bfbdb6"

[colors.normal]
black = "#131721"
red = "#f07178"
green = "#6c9b55"
yellow = "#ffb454"
blue = "#59c2ff"
magenta = "#d2a6ff"
cyan = "#4CBF99"
white = "#1f2229"

[colors.bright]
black = "#565b66"
red = "#f07178"
green = "#6c9b55"
yellow = "#ff8f40"
blue = "#59c2ff"
magenta = "#dfbfff"
cyan = "#95E6CB"
white = "#bfbdb6"
