[colors.primary]
background = "#0c0e13"
foreground = "#bfbdb6"
bright_foreground = "#f3f4f5"
dim_foreground = "#545963"

[colors.cursor]
text = "#0c0e13"
cursor = "#e6b450"

[colors.search.matches]
background = "#111d24"

[colors.search.focused_match]
background = "#3e1215"

[colors.selection]
background = "#132032"

[colors.normal]
black = "#282e3b"
red = "#da5757"
green = "#7ed962"
yellow = "#e6b450"
blue = "#5785b8"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#bfbdb6"

[colors.bright]
black = "#636975"
red = "#da5757"
green = "#7ed962"
yellow = "#e6b450"
blue = "#5785b8"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#f3f4f5"

[colors.dim]
black = "#171c24"
red = "#3e1215"
green = "#131f1c"
yellow = "#1d1f18"
blue = "#132032"
magenta = "#1d1625"
cyan = "#111d24"
white = "#545963"

[colors]
indexed_colors = [
    { index = 238, color = "#282e3b" },
    { index = 242, color = "#636975" },
    { index = 236, color = "#171c24" },

    { index = 160, color = "#da5757" },
    { index = 197, color = "#da5757" },
    { index = 52, color = "#3e1215" },

    { index = 34, color = "#7ed962" },
    { index = 40, color = "#7ed962" },
    { index = 22, color = "#131f1c" },

    { index = 226, color = "#e6b450" },
    { index = 227, color = "#e6b450" },
    { index = 220, color = "#1d1f18" },

    { index = 33, color = "#5785b8" },
    { index = 39, color = "#5785b8" },
    { index = 18, color = "#132032" },

    { index = 140, color = "#d2a6ff" },
    { index = 141, color = "#d2a6ff" },
    { index = 92, color = "#1d1625" },

    { index = 43, color = "#95e6cb" },
    { index = 44, color = "#95e6cb" },
    { index = 31, color = "#111d24" },

    { index = 249, color = "#bfbdb6" },
    { index = 250, color = "#f3f4f5" },
    { index = 248, color = "#545963" },

    { index = 196, color = "#ff0000" },

    { index = 234, color = "#0c0e13" },
    # lighter
    { index = 235, color = "#0c0e13" },
    { index = 236, color = "#1a1f28" },
    # darker
    { index = 233, color = "#060709" },
    { index = 232, color = "#000000" },
    # special
    { index = 128, color = "#132032" },

    { index = 245, color = "#bfbdb6" },
    # lighter
    { index = 246, color = "#f3f4f5" },
    { index = 247, color = "#eeeeee" },
    # darker
    { index = 244, color = "#545963" },
    { index = 243, color = "#1e222a" },
    # special
    { index = 177, color = "#5785b8" },
]
