[colors.primary]
background = "#f8f9fa"
foreground = "#5c6166"
bright_foreground = "#8a9199"
dim_foreground = "##4a505a"

[colors.cursor]
text = "#f8f9fa"
cursor = "#f2ae49"

[colors.search.matches]
background = "#111d24"

[colors.search.focused_match]
background = "#3e1215"

[colors.selection]
background = "#1c3a5b"

[colors.normal]
black = "#282e3b"
red = "#da5757"
green = "#7ed962"
yellow = "#f2ae49"
blue = "#5785b8"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#5c6166"

[colors.bright]
black = "#636975"
red = "#da5757"
green = "#7ed962"
yellow = "#f2ae49"
blue = "#5785b8"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#8a9199"

[colors.dim]
black = "#171c24"
red = "#3e1215"
green = "#131f1c"
yellow = "#1d1f18"
blue = "#1c3a5b"
magenta = "#322c3e"
cyan = "#111d24"
white = "#4a505a"

[colors]
indexed_colors = [
    { index = 238, color = "#282e3b" },
    { index = 242, color = "#636975" },
    { index = 237, color = "#171c24" },

    { index = 160, color = "#da5757" },
    { index = 197, color = "#da5757" },
    { index = 52, color = "#3e1215" },

    { index = 34, color = "#7ed962" },
    { index = 40, color = "#7ed962" },
    { index = 22, color = "#131f1c" },

    { index = 226, color = "#f2ae49" },
    { index = 227, color = "#f2ae49" },
    { index = 220, color = "#1d1f18" },

    { index = 33, color = "#5785b8" },
    { index = 39, color = "#5785b8" },
    { index = 18, color = "#1c3a5b" },

    { index = 140, color = "#d2a6ff" },
    { index = 141, color = "#d2a6ff" },
    { index = 92, color = "#322c3e" },

    { index = 43, color = "#95e6cb" },
    { index = 44, color = "#95e6cb" },
    { index = 31, color = "#111d24" },

    { index = 249, color = "#5c6166" },
    { index = 250, color = "#8a9199" },
    { index = 248, color = "#4a505a" },

    { index = 196, color = "#ff0000" },

    { index = 234, color = "#f8f9fa" },
    # lighter
    { index = 235, color = "#131721" },
    { index = 236, color = "#2e333d" },
    # darker
    { index = 233, color = "#060709" },
    { index = 232, color = "#000000" },
    # special
    { index = 128, color = "#1c3a5b" },

    { index = 245, color = "#5c6166" },
    # lighter
    { index = 246, color = "#8a9199" },
    { index = 247, color = "#eeeeee" },
    # darker
    { index = 244, color = "#4a505a" },
    { index = 243, color = "#1e222a" },
    # special
    { index = 177, color = "#5785b8" },
]

