- name: Backup previous mylsp
  include_role:
    name: backup_config
  vars:
    config_src_path: "{{ home_path }}/.local/bin/mylsp"


- name: Ensure .local/bin dir exists
  file:
    path: "{{ home_path }}/.local/bin"
    state: directory
    mode: 0755


- name: Symlink mylsp
  file:
    src: "{{ role_files_path }}/mylsp"
    dest: "{{ home_path }}/.local/bin/mylsp"
    state: link
    mode: 0755
