name: CI

on:
  push:
  pull_request:

jobs:
  code-validation:
    name: Code validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install prettier
        run: npm install --global prettier

      - name: Install typos
        run: cargo install typos-cli

      - name: Check formatting
        run: make formatter-check

      - name: Check spelling
        run: make spellchecker-check

  test_dotfiles:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.1

      - name: Install ansible
        run: pip install ansible

      - name: Test dotfiles installation
        run: make dots-install

      - name: Test if dotfiles installation is idempotent
        run: make dots-install

  test_dependencies:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Test dependencies installation
        run: make deps-install-all && make dots-install DOTS=tree

      - name: Test if dependencies installation is idempotent
        run: make deps-install-all && make dots-install DOTS=tree
