#!/bin/bash

# Hardcoded directory path
output_dir="$HOME/Desktop/notes/daily"

# Check if a date argument is provided
if [ -z "$1" ]; then
  echo "Error: No date specified. Please provide a date in YYYY-MM-DD format."
  exit 1
else
  specified_date="$1"
fi

# Calculate the weekday and human-readable date
if [[ "$(uname)" == "Darwin" ]]; then
    weekday=$(date -j -f "%Y-%m-%d" "$specified_date" "+%A")
    first_header=$(date -j -f "%Y-%m-%d" "$specified_date" "+%A, %b %d, %Y")
else
    weekday=$(date -d "$specified_date" '+%A')
    first_header=$(date -d "$specified_date" '+%A, %b %d, %Y')
fi

# Convert the weekday to lowercase
weekday_lower=$(echo "$weekday" | tr '[:upper:]' '[:lower:]')

# Define the output file path
output_file="$output_dir/${specified_date}-$weekday_lower.md"

# Check if the file already exists
if [ ! -f "$output_file" ]; then
  # Create the Markdown file with the specified content
  cat <<EOF > "$output_file"
---
date: $specified_date
weekday: $weekday_lower
---

# $first_header

## Habit Tracker

-   [ ] Exercise
-   [ ] Personal programming
-   [ ] Reading
-   [ ] Language learning
-   [ ] Note-taking
-   [ ] Guitar practice

## Tasks



## Notes
EOF
fi

# Open the file with the default editor, falling back to nvim if $EDITOR is unset
"${EDITOR:-nvim}" "$output_file"
