- name: Backup previous txc
  include_role:
    name: backup_config
  vars:
    config_src_path: "{{ home_path }}/.local/bin/txc"


- name: Ensure directory exists
  file:
    path: "{{ home_path }}/.local/bin"
    state: directory
    mode: 0755


- name: Symlink txc
  file:
    src: "{{ role_files_path }}/txc"
    dest: "{{ home_path }}/.local/bin/txc"
    state: link
    mode: 0755
